version = 1
[global]
# override the location of Lossless Scaling
# dll = "/games/Lossless Scaling"

# [[game]] # example entry
# exe = "Game.exe"
# env = "SteamDeck=0"
#
# multiplier = 3
# flow_scale = 0.7
# performance_mode = true
# hdr_mode = false
#
# experimental_present_mode = fifo
# experimental_fps_limit = 48

[[game]] # default vkcube entry
exe = "vkcube"

multiplier = 4
performance_mode = true

[[game]] # default benchmark entry
exe = "benchmark"

multiplier = 4
performance_mode = false

[[game]]
exe = "4x-fast"
multiplier = 4
performance_mode = true

[[game]]
exe = "3x-fast"
multiplier = 3
performance_mode = true

[[game]]
exe = "2x-fast"
multiplier = 2
performance_mode = true

[[game]]
exe = "4x-slow"
multiplier = 4
performance_mode = false

[[game]]
exe = "3x-slow"
multiplier = 3
performance_mode = false

[[game]]
exe = "2x-slow"
multiplier = 2
performance_mode = false
